name: foodorder
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.7.0
  flutter_screenutil: ^5.9.3
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  webview_flutter: ^4.8.0
  device_preview: ^1.2.0
  otp_text_field: ^1.1.3
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.5
  http: ^1.2.2
  shimmer: ^3.0.0
  glass: ^2.0.0+1
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  country_picker: ^2.0.26
  animated_bottom_navigation_bar: ^1.3.3
  phone_otp_verification: ^1.0.3
  lottie: ^3.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flogger: ^0.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/dlivery.json